### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by GasolSun36** [vimalabs/VIMABench#27]
Hi,

I was running the code in the readme to test if I install the environment correctly:
`from vima_bench import make

env = make(task_name="visual_manipulation")

obs = env.reset()
prompt, prompt_assets = env.prompt, env.prompt_assets

`

And I get this:

> pybullet build time: May 20 2022 19:44:17
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from vima_bench import make
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/__init__.py", line 4, in <module>
    from .env import VIMAEnvBase
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/env/__init__.py", line 1, in <module>
    from .base import VIMAEnvBase
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/env/base.py", line 12, in <module>
    from ..tasks import ALL_TASKS as _ALL_TASKS
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/__init__.py", line 7, in <module>
    from .task_suite import *
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/task_suite/__init__.py", line 1, in <module>
    from .constraint_satisfaction import *
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/task_suite/constraint_satisfaction/__init__.py", line 1, in <module>
    from .without_exceeding import WithoutExceeding
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/task_suite/constraint_satisfaction/without_exceeding.py", line 8, in <module>
    from .base import SweepObjectsToZoneBase, det_to_integer
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/task_suite/constraint_satisfaction/base.py", line 9, in <module>
    from ..base import BaseTask
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/task_suite/base.py", line 18, in <module>
    from ..components.placeholders import Placeholder
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/components/placeholders/__init__.py", line 3, in <module>
    from .placeholder_scene import PlaceholderScene
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/components/placeholders/placeholder_scene.py", line 17, in <module>
    class PlaceholderScene(Placeholder):
  File "/mnt/workspace/workgroup/sunjiashuo/VimaBench/vima_bench/tasks/components/placeholders/placeholder_scene.py", line 30, in PlaceholderScene
    image_size: tuple[int, int] = (128, 256),
TypeError: 'type' object is not subscriptable

It seems like package version error, since I tried pybullet 3.2.6 and 3.2.5, both didn't work. Can anyone share the package version?

**Comment by GasolSun36** [comment]
Problem solved, upgrade python to 3.9 above.
